# This is a forced re-deployment trigger.
theme: jekyll-theme-slate
title: Quantum Curations
description: Curated insights and smart choices for a smarter future.
header_pages:
  - about.md
  - contact.md