theme: jekyll-theme-architect
title: Quantum Curations
description: Curated insights and smart choices for a smarter future.
header_pages:
  - about.md
  - contact.md
# This is a forced re-deployment trigger.